export type EmailAttachment = {
  filename: string;
  mimeType: string;
  attachmentId: string;
  size: number;
};

export type Email = {
  /** Message-ID header (or UUID if absent) — used as deduplication key in gmail_id column */
  id: string;
  threadId?: string;
  subject: string;
  from: string;
  to: string;
  date: string;
  /** First 200 chars of body — generated by parser when not provided by source */
  snippet: string;
  body: string;
  attachments: EmailAttachment[];
  labelIds?: string[];
};

export type EmailCategory =
  | "newsletter"
  | "alert"
  | "personal"
  | "promotion"
  | "other";

export type RecommendedAction = "archive" | "keep" | "draft_reply";

export type ProcessedEmail = {
  emailId: string;
  category: EmailCategory;
  summary: string;
  todos: string[];
  recommendedAction: RecommendedAction;
  draftBody?: string;
  calendarEvents?: import("@/types/db").CalendarEvent[];
  ruleMatches?: string[];
};
